spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: <clientId>
            clientSecret: <clientSecret>
  data:
    cassandra:
      keyspace-name: database
      username: <username>
      password: <password>
      schema-action: recreate-drop-unused
      request:
        timeout: 10s
      connection:
        connect-timeout: 30s
        init-query-timeout: 30s

datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra:
  db:
    id: <ID>
    region: asia-south1
    keyspace: database
    application:
      token: <token>